AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    fce72dbc-35c2-4ee7-9967-d29b9b654cc9:
      size:
        width: 140
        height: 140
      position:
        x: 154.00390625
        'y': 95.01171875
      z: 0
      embeds: []
    3d0c680b-30cf-4bef-863b-cd0a35ce50f3:
      size:
        width: 60
        height: 60
      position:
        x: 330
        'y': 130
      z: 0
      embeds: [A, B, C, 1]
      dependson:
        - fce72dbc-35c2-4ee7-9967-d29b9b654cc9
        - ffffeeee-dddd-cccc-bbbb-aaaaaaaaaaaa
        - fce72dbc-4ee7-35c2-bbbb-aaaaaaaaaaaa
